apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: b2u43fgcj-nodejs-gitops
  description: This is GitOps manifest for b2u43fgcj-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=b2u43fgcj-nodejs
    backstage.io/kubernetes-id: b2u43fgcj-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: b2u43fgcj-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:b2u43fgcj-nodejs
