apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b2u43fgcj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b2u43fgcj-nodejs 
  name: b2u43fgcj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: b2u43fgcj-nodejs 
